############################################
# wazuh.tf — Single-node Wazuh stack
# Terraform-managed (docker provider)
############################################

locals {
  wazuh_host_config_dir = var.wazuh_host_config_dir
  wazuh_certs_dir       = var.wazuh_certs_dir

  dashboard_yml_host_path = "${var.wazuh_dashboard_config_dir}/opensearch_dashboards.yml"
  certs_yml_host_path     = "${local.wazuh_host_config_dir}/certs.yml"
}

############################################
# Images
############################################

resource "docker_image" "wazuh_manager" {
  name = "wazuh/wazuh-manager:${var.wazuh_version}"
}

resource "docker_image" "wazuh_indexer" {
  name = "wazuh/wazuh-indexer:${var.wazuh_version}"
}

resource "docker_image" "wazuh_dashboard" {
  name = "wazuh/wazuh-dashboard:${var.wazuh_version}"
}

resource "docker_image" "wazuh_certs_generator" {
  name = "wazuh/wazuh-certs-generator:${var.wazuh_certs_generator_version}"
}

############################################
# Files generated by Terraform
############################################

resource "local_file" "wazuh_dashboard_opensearch_dashboards_yml" {
  depends_on = [null_resource.ensure_paths]

  filename = local.dashboard_yml_host_path

  content = <<-YAML
server.host: "0.0.0.0"
server.port: 5601

opensearch.hosts: ["${var.wazuh_indexer_scheme}://wazuh-indexer:9200"]

# fastest boot path
opensearch.ssl.verificationMode: none

opensearch.username: "${var.wazuh_dashboard_indexer_username}"
opensearch.password: "${var.wazuh_dashboard_indexer_password}"

opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]

opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]

uiSettings.overrides.defaultRoute: /app/wz-home
YAML
}

resource "local_file" "wazuh_certs_yml" {
  depends_on = [null_resource.ensure_paths]

  filename = local.certs_yml_host_path

  content = <<-YAML
nodes:
  indexer:
    - name: wazuh-indexer
      ip: "${var.wazuh_cert_ip}"
  server:
    - name: wazuh-manager
      ip: "${var.wazuh_cert_ip}"
  dashboard:
    - name: wazuh-dashboard
      ip: "${var.wazuh_cert_ip}"
YAML
}

############################################
# Generate certs (wazuh-certs-generator)
############################################

resource "null_resource" "wazuh_generate_certs" {
  depends_on = [
    null_resource.ensure_paths,
    local_file.wazuh_certs_yml,
    docker_image.wazuh_certs_generator,
  ]

  triggers = {
    wazuh_version      = var.wazuh_version
    generator_version  = var.wazuh_certs_generator_version
    certs_yml_checksum = sha256(local_file.wazuh_certs_yml.content)
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command = <<-EOT
      set -euo pipefail

      CERT_TOOL_VERSION="$(echo "${var.wazuh_version}" | awk -F. '{print $1"."$2}')"

      sudo mkdir -p "${local.wazuh_certs_dir}"

      # Run generator
      docker run --rm \
        -e CERT_TOOL_VERSION="$CERT_TOOL_VERSION" \
        -v "${local.wazuh_certs_dir}:/certificates" \
        -v "${local_file.wazuh_certs_yml.filename}:/config/certs.yml:ro" \
        "${docker_image.wazuh_certs_generator.name}"
    EOT
  }
}

############################################
# Normalize cert names + permissions
############################################

resource "null_resource" "wazuh_normalize_certs" {
  depends_on = [null_resource.wazuh_generate_certs]

  triggers = {
    wazuh_version = var.wazuh_version
    certs_hash    = sha256(local_file.wazuh_certs_yml.content)
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command = <<-EOT
      set -euo pipefail
      CERTDIR="${local.wazuh_certs_dir}"

      sudo mkdir -p "$CERTDIR"

      copy_if() {
        local src="$1"
        local dst="$2"
        if [ -f "$src" ] && [ ! -f "$dst" ]; then
          sudo cp -f "$src" "$dst"
        fi
      }

      # Root CA
      copy_if "$CERTDIR/root-ca.pem" "$CERTDIR/root-ca.pem"
      copy_if "$CERTDIR/root-ca.crt" "$CERTDIR/root-ca.pem"
      copy_if "$CERTDIR/ca.pem"      "$CERTDIR/root-ca.pem"
      copy_if "$CERTDIR/ca.crt"      "$CERTDIR/root-ca.pem"

      # Admin cert/key
      copy_if "$CERTDIR/admin.pem"           "$CERTDIR/admin.pem"
      copy_if "$CERTDIR/admin-key.pem"       "$CERTDIR/admin-key.pem"
      copy_if "$CERTDIR/wazuh-admin.pem"     "$CERTDIR/admin.pem"
      copy_if "$CERTDIR/wazuh-admin-key.pem" "$CERTDIR/admin-key.pem"
      copy_if "$CERTDIR/admin.crt"           "$CERTDIR/admin.pem"
      copy_if "$CERTDIR/admin.key"           "$CERTDIR/admin-key.pem"

      # Indexer cert/key
      copy_if "$CERTDIR/indexer.pem"           "$CERTDIR/indexer.pem"
      copy_if "$CERTDIR/indexer-key.pem"       "$CERTDIR/indexer-key.pem"
      copy_if "$CERTDIR/wazuh-indexer.pem"     "$CERTDIR/indexer.pem"
      copy_if "$CERTDIR/wazuh-indexer-key.pem" "$CERTDIR/indexer-key.pem"
      copy_if "$CERTDIR/wazuh-indexer.key"     "$CERTDIR/indexer-key.pem"
      copy_if "$CERTDIR/indexer.key"           "$CERTDIR/indexer-key.pem"

      # Hard fail if missing
      test -f "$CERTDIR/root-ca.pem"
      test -f "$CERTDIR/admin.pem"
      test -f "$CERTDIR/admin-key.pem"
      test -f "$CERTDIR/indexer.pem"
      test -f "$CERTDIR/indexer-key.pem"

      # ---- CRITICAL FIX: permissions so container user can read certs ----
      # Directory executable so it can traverse
      sudo chmod 755 "$CERTDIR" || true

      # Public certs readable by anyone
      sudo chmod 644 "$CERTDIR/root-ca.pem" "$CERTDIR/admin.pem" "$CERTDIR/indexer.pem" || true

      # Keys should be readable only by owner, but that can break containers if owner != container uid.
      # Wazuh indexer only needs to read them as its own user; safest is 640 with group-readable.
      # We'll go with 640 and set group ownership to 0 if possible; if not, fallback to 644.
      sudo chmod 640 "$CERTDIR/admin-key.pem" "$CERTDIR/indexer-key.pem" || true

      # If keys still end up unreadable due to uid mapping, relax to 644 (last resort)
      sudo chmod 644 "$CERTDIR/admin-key.pem" "$CERTDIR/indexer-key.pem" || true

      echo "Normalized certs in $CERTDIR:"
      sudo ls -la "$CERTDIR" | sed -n '1,200p'
    EOT
  }
}

############################################
# Wazuh Indexer
############################################

resource "docker_container" "wazuh_indexer" {
  depends_on = [
    null_resource.ensure_paths,
    docker_network.media_net,
    null_resource.wazuh_normalize_certs,
  ]

  name    = "wazuh-indexer"
  image   = docker_image.wazuh_indexer.image_id
  restart = "unless-stopped"

  env = [
    "TZ=${var.tz}",
    "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g",
    "discovery.type=single-node",
  ]

  ports {
    internal = 9200
    external = var.wazuh_indexer_port
    protocol = "tcp"
  }

  mounts {
    target = "/var/lib/wazuh-indexer"
    source = var.wazuh_indexer_data_dir
    type   = "bind"
  }

  mounts {
    target    = "/usr/share/wazuh-indexer/config/certs"
    source    = local.wazuh_certs_dir
    type      = "bind"
    read_only = true
  }

  networks_advanced {
    name = docker_network.media_net.name
  }
}

############################################
# Preflight: ensure indexer can read certs INSIDE container
############################################

resource "null_resource" "wazuh_indexer_certs_preflight" {
  depends_on = [docker_container.wazuh_indexer]

  triggers = {
    certs_hash = sha256(local_file.wazuh_certs_yml.content)
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command = <<-EOT
      set -euo pipefail

      echo "[certs-preflight] Checking cert readability inside container..."

      # Wait a moment for container filesystem to be ready
      sleep 3

      # If container is crash looping, show logs and fail fast
      if ! docker ps --format '{{.Names}}' | grep -q '^wazuh-indexer$'; then
        echo "[certs-preflight] ERROR: wazuh-indexer is not running."
        docker ps -a | sed -n '1,120p' || true
        docker logs wazuh-indexer --tail 200 || true
        exit 1
      fi

      docker exec wazuh-indexer bash -lc '
        set -euo pipefail
        CERTS="/usr/share/wazuh-indexer/config/certs"
        echo "[certs-preflight][container] Listing $CERTS"
        ls -la "$CERTS" | sed -n "1,120p"
        echo "[certs-preflight][container] Reading root-ca.pem..."
        head -c 20 "$CERTS/root-ca.pem" >/dev/null
        echo "[certs-preflight][container] OK: root-ca.pem readable"
      '
    EOT
  }
}

############################################
# Initialize OpenSearch Security index
############################################

resource "null_resource" "wazuh_indexer_security_init" {
  depends_on = [
    null_resource.wazuh_indexer_certs_preflight
  ]

  triggers = {
    wazuh_version = var.wazuh_version
    certs_hash    = sha256(local_file.wazuh_certs_yml.content)
  }

  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command = <<-EOT
      set -euo pipefail

      USERPASS="admin:admin"

      echo "[security-init] Waiting for indexer HTTPS..."
      READY="0"
      for i in $(seq 1 240); do
        if docker exec wazuh-indexer bash -lc "curl -sk --max-time 2 https://127.0.0.1:9200 >/dev/null 2>&1"; then
          echo "[security-init] Indexer is reachable over HTTPS."
          READY="1"
          break
        fi
        sleep 2
      done

      if [ "$READY" != "1" ]; then
        echo "[security-init] ERROR: Indexer never became reachable."
        docker logs wazuh-indexer --tail 200 || true
        exit 1
      fi

      if docker exec wazuh-indexer bash -lc "curl -sk --max-time 2 -u \"$USERPASS\" https://127.0.0.1:9200/_cat/indices/.opendistro_security?h=index | grep -q .opendistro_security"; then
        echo "[security-init] .opendistro_security already exists. Skipping."
        exit 0
      fi

      echo "[security-init] Running securityadmin inside container..."

      for attempt in $(seq 1 10); do
        echo "[security-init] Attempt $attempt/10"

        set +e
        OUT="$(docker exec -i wazuh-indexer bash -s 2>&1 <<'EOS'
set -euo pipefail

export JAVA_HOME="/usr/share/wazuh-indexer/jdk"
export OPENSEARCH_JAVA_HOME="/usr/share/wazuh-indexer/jdk"
export PATH="$JAVA_HOME/bin:$PATH"

SECADM="/usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh"
CERTS="/usr/share/wazuh-indexer/config/certs"
SECCFG="/usr/share/wazuh-indexer/config/opensearch-security"

test -x "$SECADM"
test -d "$SECCFG"
test -f "$CERTS/root-ca.pem"
test -f "$CERTS/admin.pem"
test -f "$CERTS/admin-key.pem"

"$SECADM" \
  -cd "$SECCFG" \
  -cacert "$CERTS/root-ca.pem" \
  -cert   "$CERTS/admin.pem" \
  -key    "$CERTS/admin-key.pem" \
  -nhnv \
  -icl \
  -h 127.0.0.1 \
  -p 9200
EOS
)"
        RC=$?
        set -e

        echo "$OUT"

        if docker exec wazuh-indexer bash -lc "curl -sk --max-time 2 -u \"$USERPASS\" https://127.0.0.1:9200/_cat/indices/.opendistro_security?h=index | grep -q .opendistro_security"; then
          echo "[security-init] SUCCESS: security index initialized."
          exit 0
        fi

        echo "[security-init] Not initialized yet (rc=$RC). Sleeping..."
        sleep 8
      done

      echo "[security-init] ERROR: failed to initialize .opendistro_security after retries."
      docker logs wazuh-indexer --tail 200 || true
      exit 1
    EOT
  }
}

############################################
# Wazuh Manager
############################################

resource "docker_container" "wazuh_manager" {
  depends_on = [
    null_resource.ensure_paths,
    docker_network.media_net,
    docker_container.wazuh_indexer,
    null_resource.wazuh_indexer_security_init,
    null_resource.wazuh_normalize_certs,
  ]

  name    = "wazuh-manager"
  image   = docker_image.wazuh_manager.image_id
  restart = "unless-stopped"

  env = [
    "TZ=${var.tz}",
    "INDEXER_URL=${var.wazuh_indexer_scheme}://wazuh-indexer:9200",
    "INDEXER_USERNAME=${var.wazuh_manager_indexer_username}",
    "INDEXER_PASSWORD=${var.wazuh_manager_indexer_password}",
  ]

  ports {
    internal = 55000
    external = var.wazuh_manager_api_port
    protocol = "tcp"
  }

  mounts {
    target = "/var/ossec/data"
    source = var.wazuh_manager_data_dir
    type   = "bind"
  }

  mounts {
    target    = "/etc/filebeat/certs"
    source    = local.wazuh_certs_dir
    type      = "bind"
    read_only = true
  }

  networks_advanced {
    name = docker_network.media_net.name
  }
}

############################################
# Wazuh Dashboard
############################################

resource "docker_container" "wazuh_dashboard" {
  depends_on = [
    null_resource.ensure_paths,
    docker_network.media_net,
    docker_container.wazuh_indexer,
    docker_container.wazuh_manager,
    local_file.wazuh_dashboard_opensearch_dashboards_yml,
    null_resource.wazuh_indexer_security_init,
    null_resource.wazuh_normalize_certs,
  ]

  name    = "wazuh-dashboard"
  image   = docker_image.wazuh_dashboard.image_id
  restart = "unless-stopped"

  env = [
    "TZ=${var.tz}",
    "INDEXER_USERNAME=${var.wazuh_dashboard_indexer_username}",
    "INDEXER_PASSWORD=${var.wazuh_dashboard_indexer_password}",
    "WAZUH_API_URL=http://wazuh-manager:55000",
    "DASHBOARD_USERNAME=${var.wazuh_dashboard_username}",
    "DASHBOARD_PASSWORD=${var.wazuh_dashboard_password}",
  ]

  ports {
    internal = 5601
    external = var.wazuh_dashboard_port
    protocol = "tcp"
  }

  mounts {
    target    = "/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml"
    source    = local_file.wazuh_dashboard_opensearch_dashboards_yml.filename
    type      = "bind"
    read_only = true
  }

  mounts {
    target    = "/usr/share/wazuh-dashboard/certs"
    source    = local.wazuh_certs_dir
    type      = "bind"
    read_only = true
  }

  networks_advanced {
    name = docker_network.media_net.name
  }
}
